### ISSUE TITLE
missing required field: agency_id for SPNV-BW

### ISSUE THREAD

**Issue by hbruch** [mfdz/gtfs-hub#13]
```
patching SPNV-BW GTFS feed using OBA GTFS Transformer & config/gtfs-rules/SPNV-BW.rule
docker run -i --rm -v /home/mfdz/gtfs-hub/config/gtfs-rules:/cfg -v /home/mfdz/gtfs-hub/data/gtfs:/data mfdz/otp-data-tools java -Xmx20g -jar one-busaway-gtfs-transformer/onebusaway-gtfs-transformer-cli.jar --transform=/cfg/SPNV-BW.rule /data/SPNV-BW.raw.gtfs.zip /data/SPNV-BW.filtered.gtfs
2021-05-10 13:22:40,900 INFO  [GtfsTransformerMain.java:200] : input path: /data/SPNV-BW.raw.gtfs.zip
2021-05-10 13:22:41,006 INFO  [GtfsTransformerMain.java:205] : output path: /data/SPNV-BW.filtered.gtfs
2021-05-10 13:22:41,023 INFO  [GtfsTransformer.java:195] : reading gtfs from /data/SPNV-BW.raw.gtfs.zip
2021-05-10 13:22:41,034 INFO  [GtfsTransformer.java:199] : found lastModifiedTime of Thu May 06 10:52:58 CEST 2021
2021-05-10 13:22:41,035 INFO  [GtfsReader.java:169] : reading entities: org.onebusaway.gtfs.model.Agency
2021-05-10 13:22:41,051 INFO  [GtfsReader.java:169] : reading entities: org.onebusaway.gtfs.model.Block
2021-05-10 13:22:41,051 INFO  [GtfsReader.java:169] : reading entities: org.onebusaway.gtfs.model.ShapePoint
2021-05-10 13:24:38,915 INFO  [GtfsReader.java:169] : reading entities: org.onebusaway.gtfs.model.Note
2021-05-10 13:24:38,998 INFO  [GtfsReader.java:169] : reading entities: org.onebusaway.gtfs.model.Area
2021-05-10 13:24:38,998 INFO  [GtfsReader.java:169] : reading entities: org.onebusaway.gtfs.model.Route
org.onebusaway.csv_entities.exceptions.CsvEntityIOException: io error: entityType=org.onebusaway.gtfs.model.Route path=routes.txt lineNumber=3
	at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:161)
	at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:120)
	at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:115)
	at org.onebusaway.gtfs.serialization.GtfsReader.run(GtfsReader.java:171)
	at org.onebusaway.gtfs.serialization.GtfsReader.run(GtfsReader.java:159)
	at org.onebusaway.gtfs_transformer.GtfsTransformer.readGtfs(GtfsTransformer.java:204)
	at org.onebusaway.gtfs_transformer.GtfsTransformer.run(GtfsTransformer.java:160)
	at org.onebusaway.gtfs_transformer.GtfsTransformerMain.runApplication(GtfsTransformerMain.java:268)
	at org.onebusaway.gtfs_transformer.GtfsTransformerMain.run(GtfsTransformerMain.java:112)
	at org.onebusaway.gtfs_transformer.GtfsTransformerMain.main(GtfsTransformerMain.java:91)
Caused by: org.onebusaway.csv_entities.exceptions.MissingRequiredFieldException: missing required field: agency_id
	at org.onebusaway.gtfs.serialization.mappings.RouteAgencyFieldMappingFactory$RouteAgencyFieldMapping.translateFromCSVToObject(RouteAgencyFieldMappingFactory.java:72)
	at org.onebusaway.csv_entities.IndividualCsvEntityReader.readEntity(IndividualCsvEntityReader.java:131)
	at org.onebusaway.csv_entities.IndividualCsvEntityReader.handleLine(IndividualCsvEntityReader.java:98)
	at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:157)
	... 9 more
```

**Comment by mariomurrent-softwaresolutions** [comment]
And how was this solved?
